apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: d5ptej753-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-e8be776a06.86sc.p3.openshiftapps.com/rhtap/rhtap-qe:7fac0cdba662a29af467997fb6f89ae59840e777@sha256:a3fd6716985eb9306fbf218b3eece1d8d14de345edc7d8276318dc522e5b9191
          name: container-image
